#!/bin/bash
set -e

jshint immunity_monitoring/device/static/monitoring/js/*.js
jshint immunity_monitoring/monitoring/static/monitoring/js/*.js
stylelint immunity_monitoring/device/static/monitoring/css/*.css
stylelint immunity_monitoring/monitoring/static/monitoring/css/*.css


immunity-qa-check \
  --migration-path "./immunity_monitoring/check/migrations \
                    ./immunity_monitoring/device/migrations \
                    ./immunity_monitoring/monitoring/migrations" \
  --migration-module "check device_monitoring monitoring"

echo ''
echo 'Running checks for SAMPLE_APP'
SAMPLE_APP=1 immunity-qa-check \
    --skip-isort \
    --skip-flake8 \
    --skip-checkmigrations \
    --skip-checkendline \
    --skip-checkcommit \
    --skip-black \
    --csslinter \
    --jslinter \
    --migration-path "./tests/immunity2/sample_check/migrations/ \
                      ./tests/immunity2/sample_device_monitoring/migrations/ \
                      ./tests/immunity2/sample_monitoring/migrations/" \
    --migration-module "sample_check sample_device_monitoring sample_monitoring"
