# Generated by Django 3.1.2 on 2020-12-20 06:15


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_monitoring', '0001_squashed_0002_devicemonitoring'),
    ]

    operations = [
        # NOTE: Usage of "Monitoring Template" is deprecated in favour of
        # "immunity-immunity-monitoring" package. See
        # https://github.com/edge-servers/openwrt-immunity-monitoring#openwrt-immunity-monitoring
        migrations.RunPython(
            migrations.RunPython.noop, reverse_code=migrations.RunPython.noop
        )
    ]
